# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - educatio-backend

on:
  push:
    branches:
      - Version1.0   # asegúrate que esta es tu rama de trabajo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'   # versión estable soportada por Azure

      - name: Install dependencies
        run: |
          cd api-nomina-nodejs
          npm install

      - name: Build app (opcional si usas TS/Babel)
        run: |
          cd api-nomina-nodejs
          npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'educatio-backend'   # nombre de tu App Service
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./api-nomina-nodejs
